# Composing Suspending Functions

## Sequential by default

- 어딘가에 아래와 같이 2개의 suspending function이 정의되어 있다고 하자.  
  오래 걸리는 작업을 하는 것처럼 하기 위해 내부에서 1초 동안 delay를 주게 했다.

```kt
suspend fun doSomethingUsefulOne(): Int {
    delay(1000L)
    return 13
}

suspend fun doSomethingUsefulTwo(one: Int): Int {
    delay(1000L)
    return if(one == 13) 29
    else 0
}
```

- 만약 `doSomethingUsefuleOne()`이 먼저 실행된 후에 `doSomethingUsefulTwo()`가 실행되기를 바란다면 어떨까?  
  두 번째로 실행되는 함수의 동작이 첫번째로 실행되는 함수의 결과에 의존하는 경우 등 말이다.

- 이 경우에 우리는 그냥 평소처럼 코드를 작성하면 된다. 그 이유는 Coroutine 내부의 코드들은 다른 일반적인 코드들과 같이  
  기본적으로 순차적으로 실행되기 때문이다. 아래의 예시는 이것을 실행 시간을 측정함으로써 보여준다.

```kt
suspend fun main() {
    val time = measureTimeMillis {
        val one = doSomethingUsefulOne()
        val two = doSomethingUsefulTwo()
        println("The answer is ${one + two}")
    }
    println("Completed in $time ms")
}

/*
Output:
The answer is 42
Completed in 2024 ms
*/
```

- 42가 출력되었다는 것은 `doSomethingUsefulTwo()`가 `doSomethingUsefulOne()`의 실행이 끝난 뒤에 호출되어  
  실행되었다는 의미이다.

---

## Concurrent using async

- 이제 `doSomethingUsefulOne()`과 `doSomethingUsefulTwo()`의 실행 순서가 서로 의존성이 없고,  
  이 둘을 병렬적으로 동시에 수행하여 결과값을 빠르게 얻고 싶으면 어떻게 해야할까?  
  정답은 `async`를 사용하는 것이다.

- 개념적으로 `async`는 `launch`와 매우 유사하다. 이 함수는 경량회된 thread와 같은 coroutine을 다른 coroutine들과  
  병렬적으로 동시에 수행되도록 해준다. `launch`는 내부 블록에서 수행되는 결과가 전혀 포함되지 않은 `Job`을 반환하는 반면,  
  `async`는 경량화된 future객체로, 결과값을 반환해줄 것이라는 약속(promise)를 표현하는 `Deferred` 객체를 반환한다.  
  deferred 결과에 대해서는 `.await()`를 사용하여 결과값을 참조할 수 있다. 참고로 `Deferred` 또한 `Job`이기에  
  필요 시 cancel할 수 있다.

```kt
suspend fun doSomethingUsefulOne(): Int {
    delay(1000L)
    return 13
}

suspend fun doSomethingUsefulTwo(): Int {
    delay(1000L)
    return 29
}

suspend fun measureTime() = coroutineScope {
    val time = measureTimeMillis {
        val one = async { doSomethingUsefulOne() }
        val two = async { doSomethingUsefulTwo() }
        println("The answer is ${one.await() + two.await()}")
    }
    println("Completed in $time ms")
}
suspend fun main() {
    measureTime()
}

/*
Output:
The answer is 42
Completed in 1036 ms
*/
```

- 위 결과는 기존에 순차적으로 진행된 작업에 비해 병렬적으로 동시에 수행되기에 2배 가량 빠르다.  
  Coroutine들이 병렬적으로 동시에 수행되게끔 하기 위해서는 명시적으로 설정해줘야 함을 주의하자.

> `.await()`를 호출하지 않으면 one, two는 수행되지 않는다.

---

## Lazily started async

- 선택적으로 `async()`의 start 매개변수에 `CoroutineStart.LAZY`를 지정함으로써 `async`의 작업이 lazy하게 수행되게 할 수 있다.  
  이 인자가 주어지면, coroutine은 해당 작업을 참조하는 변수에 `await()` 또는 `start()`가 호출될 때만 작업을 수행한다.

```kt
suspend fun measureTime() = coroutineScope {
    val time = measureTimeMillis {
        val one = async(start = CoroutineStart.LAZY) { doSomethingUsefulOne() }
        val two = async(start = CoroutineStart.LAZY) { doSomethingUsefulTwo() }
        one.start()
        two.start()
        println("The answer is ${one.await() + two.await()}")
    }
    println("Completed in $time ms")
}

/*
Output:
The answer is 42
Completed in 1040 ms
*/
```

- 위 예시 코드에는 2개의 coroutine이 정의되어 있지만, 이전 코드 처럼 수행되지는 않는다.  
  개발자는 해당 coroutine 작업을 참조하는 변수에 대해 `start()`를 호출하여 언제 작업을 수행할지 지정할 수 있다.  
  위 코드는 one을 start, two를 start, 그리고 마지막에 둘 다에 대해 `await()`를 호출하여 작업이 끝나기를 기다린다.

- 유의할 점은, `.start()`를 호출하지 않고 `.await()`를 호출한다면 순차적으로 실행된다.  
  이는 `await()`가 coroutine을 실행하고 결과를 기다리기 때문인데, 이는 lazy를 잘못 사용하는 것이다.  
  즉, 만약 `one.start()`와 `two.start()`를 빼버리면 아래 처럼 순차적인 결과가 나온다.

```
The answer is 42
Completed in 2047 ms
```

---

## Async-style functions

- 위 예시에서는 함수를 `async { .. }` 블록에 넣어 async처리를 했지만, 함수 자체를 비동기적으로 작동하도록 선언할 수도 있다.  
  이때 사용하는 것은 `GlobalScope.async`인데, 이는 구조적 병렬(Structured Concurrency)를 다른 코드에서  
  지켜주기 위해 사용된다. 관례적으로 `***Async`와 같은 형식으로 함수를 네이밍하여 해당 함수가 비동기적으로 작동함을 표시해준다.

```kt
// somethingUsefulOneAsync의 반환형은  Deferred<Int> 이다.
@OptIn(DelicateCoroutinesApi::class)
fun somethingUsefulOneAsync() = GlobalScope.async {
    doSomethingUsefulOne()
}

// somethingUsefulTwoAsync의 반환형은 Deferred<Int> 이다.
@OptIn(DelicateCoroutinesApi::class)
fun somethingUsefulTwoAsync() = GlobalScope.async {
    doSomethingUsefulTwo()
}
```

- `***Async` 함수가 Suspending Function이 아님에 주의하자. 이런 함수들은 어디서든 사용될 수 있다는 뜻이다.  
  하지만 이 함수들을 호출하는 곳에서의 실행은 비동기적(병렬적)으로 된다.

```kt
fun main() {
    val time = measureTimeMillis {

        // async 함수를 coroutine 밖에서 호출한다.
        val one = somethingUsefulOneAsync()
        val two = somethingUsefulTwoAsync()

        // 하지만 결과값을 기다리는 것은 suspending 또는 blocking이 필수적으로 필요하다.
        // 여기서는 runBlocking을 사용하여 main thread가 one, two가 끝날 때까지 기다리도록 한다.
        runBlocking {
            println("The answer is ${one.await() + two.await()}")
        }
    }
    println("Completed in $time ms")
}

/*
Output:
The answer is 42
Completed in 1053 ms
*/
```

- 만약 one 변수를 선언하는 부분과 `one.await()`가 호출되는 부분 사이에 예외가 발생하면 어떻게 될까?  
  일반적으로 전역 에러 핸들러(Global Error Handler)가 이 예외를 잡아 로깅 및 report를 한 후 프로그램이  
  다른 작업을 수행할 것이다. 하지만 위 코드대로라면 예외가 발생해도 `somethingUsefulOneAsync()`는 백그라운드에서  
  작업을 계속하고 있게 된다. 따라서 위처럼 코드를 작성하는 것은 Kotlin에서는 절대 권장되지 않는다.

> 즉, Structured Concurrency를 위반하는 코드 작성이 권장되지 않는다는 것이다.

---

## Structured Concurrency with async

- 다시 위에서 작성했던 예시 코드 중 하나로 돌아가보자.  
  `doSomethingUsefulOne()`과 `doSomethingTwo()`를 병렬적으로 수행한 후, 그 둘의 결과를 더한 값을 반환하는 함수를 보자.  
  `async` coroutine builder는 `CoroutineScope`의 연장선에서 만들어졌기 때문에, coroutine이 수행되는 코드를  
  CoroutineScope내에 넣을 수 있다.

```kt
suspend fun concurrentSum(): Int = coroutineScope {
    val one = async { doSomethingUsefulOne() }
    val two = async { doSomethingUsefulTwo() }
    one.await() + two.await()
}
```

- 위 코드 처럼 병렬적으로 수행되는 함수(async를 사용하여)가 CoroutineScope내에서 작동되도록 하면 코드가 수행되는 도중 예외가 발생했을 때  
  해당 coroutineScope내에서 작동하던 모든 coroutine들의 작업이 중단되는 것을 보장할 수 있다.

```kt
suspend fun main() {
    val time = measureTimeMillis {
        println("The answer is ${concurrentSum()}")
    }
    println("Completed in $time ms")
}

/*
Output:
The answer is 42
Completed in 1045 ms
*/
```

- 결과값을 보면 하나의 coroutineScope내의 각 함수가 병렬적으로 실행되었음을 알 수 있다.

- Coroutine이 중단되는 Cancellation은 coroutine들이 정의된 계층에 따라 전파된다.

```kt
fun main() = runBlocking<Unit> {
    try {
        failedConcurrentSum()
    } catch(e: ArithmeticException) {
        println("Computation failed with ArithmeticException.")
    }
}

suspend fun failedConcurrentSum(): Int = coroutineScope {
    val one = async<Int> {
        try {
	    // 매우 긴 시간 동안 delay 시킨다.
	    // (two의 작업이 끝난다는 것을 보장하기 위해)
            delay(Long.MAX_VALUE)
            42
        } finally {
            println("First child was cancelled.")
        }
    }
    val two = async<Int> {
        println("Second child throws an exception.")
        throw ArithmeticException()
    }
    one.await() + two.await()
}

/*
Output:
Second child throws an exception.
First child was cancelled.
Computation failed with ArithmeticException.
*/
```

- 위에서는 two의 작업에서 예외가 발생하여 one의 작업도 취소되었고, 애초에 one과 two의 작업을 호출하는 `failedConcurrentSum()`에도  
  예외인 `ArithmeticException`이 그대로 전파되어 catch 블록에서 catch되었다.

---

- [참고 문서](https://kotlinlang.org/docs/composing-suspending-functions.html)
